### ISSUE TITLE
Update Navigation Module in Wiki

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/microcontrollers#11]
Refs LakeMaps/boat#18

The page in question: [Navigation Module Commands](https://github.com/LakeMaps/microcontrollers/wiki/Navigation-Module-Commands)—are we working with this still or should remove this page from the Wiki?

**Comment by arandell93** [comment]
Since there is no navigation module anymore, this page is obsolete.
However, I suggest using the compact GPS data format for when you package the GPS data to send over the wireless. The datatypes indicated were what was used for the GPS library ([TinyGPS](https://github.com/mikalhart/TinyGPS)) I was using on the Arduino.
The NMEA sentences send all of the data using ASCII, so it will need to be converted from there first.

Byte|	Description|	Valid Range
|:---:|:---:|:---:|
0 to 3|Latitude|float (4 bytes)
4 to 7|Longitude|float 4 bytes)
8 to 11|Altitude (m)|float (4 bytes)
12 to 15|Course|float (4 bytes)
16 to 19|Speed (m/s)|float (4 bytes)
20 to 21|Satellites|unsigned short (2 bytes)
22 to 25|HDOP (in 1/100ths)|unsigned long (4 bytes)
26 to 29|Age of Data (ms)|unsigned long (4 bytes)
